### ISSUE TITLE
After logging in, you see the sign up page for a few seconds

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma-cloud-feedback#108]
Reproduction:

* navigate to https://app.prisma.sh/. If you are logged in, log out.
* click the Log In button

![image](https://user-images.githubusercontent.com/1780597/37714971-1ed78660-2d1b-11e8-9025-968423d21ae9.png)

* login

Now, you will see the same view as in the screenshot above for a couple of seconds. Then you are successfully logged in.

Instead, a loading animation or something else should be shown.

**Comment by timsuchanek** [comment]
Fixed in the latest version.
