### ISSUE TITLE
Databrowser: When updating nodes, don't include "connect" if relation didn't change

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma-cloud-feedback#135]
## Bug

This is caused by [this](https://github.com/graphcool/prisma/issues/2249) and currently blocks updating nodes in a required relation using the Databrowser. A workaround is to use the Playground for such updates.

## Reproduction

```graphql
type A {
  id: ID! @unique
  b: B! @relation(name: "AB")
  name: String!
}

type B {
  id: ID! @unique
  a: A! @relation(name: "AB")
  name: String!
}
```

Create nodes:

```graphql
mutation a {
  createA(data: {
    name: "A"
    b: {
      create: {
        name: "B"
      }
    }
  }) {
    id # A_ID
    b {
      id # B_ID
    }
  }
}
```

Navigate to databrowser, try to rename `a`. You'll get this error:

![image](https://user-images.githubusercontent.com/1780597/39131315-759ccba0-470f-11e8-9c01-dac347c3fc16.png)

This is the **current** mutation:

```
{"query":"mutation ($data: AUpdateInput! $id: ID!) {\n      updateA(data: $data where: {id: $id}) {\n    id\n    b { id }\n    name\n      }\n    }","variables":{"data":{"b":{"connect":{"id":"cjgcawtrng80k0b580zz1w1se"}},"name":"A2"},"id":"cjgcawtrng80j0b58y65z8wc3"}}
```

Instead, this is the **proposed** mutation:

```
{"query":"mutation ($data: AUpdateInput! $id: ID!) {\n      updateA(data: $data where: {id: $id}) {\n    id\n    b { id }\n    name\n      }\n    }","variables":{"data":{"name":"A2"},"id":"cjgcawtrng80j0b58y65z8wc3"}}
```

Omitting `connect` allows the mutation to go through as expected.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
