### ISSUE TITLE
Update terminology to 1.7

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma-cloud-feedback#138]
From [the upgrade guide](https://www.prisma.io/docs/1.7/reference/upgrade-guides/upgrading-prisma/upgrade-to-1.7-iquaecuj6b):

> Prisma Clusters are renamed to Prisma Servers
> Development Clusters are renamed to Prisma Sandbox

**Comment by schickling** [comment]
- [ ] search field

![image](https://user-images.githubusercontent.com/1567498/40886880-0ec829b4-6740-11e8-9de2-bd87a444df23.png)

**Comment by schickling** [comment]
- [ ] dev cluster

![image](https://user-images.githubusercontent.com/1567498/40886885-32acd6e0-6740-11e8-995a-2ae1cc6c6c0c.png)

**Comment by schickling** [comment]
- [ ] url

![image](https://user-images.githubusercontent.com/1567498/40886888-442e3850-6740-11e8-8f8c-185bd9492d50.png)
