### ISSUE TITLE
Data Browser does not show data (from Digital Ocean Docker setup)

### ISSUE THREAD

**Issue by reinvanimschoot** [prismagraphql/prisma-cloud-feedback#142]
I have set up a fresh Prisma server (1.8) on Digital Ocean in a Docker container, with postgres as database. I then successfully connected my endpoint to my Prisma dashboard (great feature btw).

However, when I want to access my data in the data browser, it gets stuck on the loading screen.

A quick look at the console showed an error with insecure http loading.

![screen shot 2018-05-17 at 10 33 28](https://user-images.githubusercontent.com/35171567/40166042-dd2a25b8-59bd-11e8-82b7-bf3a404234d7.png)

**Comment by marktani** [comment]
Thanks for bringing this up @reinvanimschoot, this is high on our list 🙂

**Comment by timsuchanek** [comment]
Yes, and because of that we just rolled out a fix 🙂
