### ISSUE TITLE
Stats not available for any service deployed on prisma.io

### ISSUE THREAD

**Issue by agonbina** [prismagraphql/prisma-cloud-feedback#146]
I have deployed a couple of services to a "connected cluster"(running on AWS) and also to the public server(prisma-eu1) but I do not see any kind of statistics in the "Dashboard" tab for that specific service. I made sure to generate enough requests (in the thousands) but I still do not see any statistics.

The workspace name is `agon-bina`

**Comment by dpetrick** [comment]
We are aware of an ongoing problem with our backing metrics provider and actively work on a resolution.

**Comment by agonbina** [comment]
@dpetrick I have removed my services running on the shared servers hosted by Prisma and deployed them on my "connected cluster" running on AWS. For these I still do not see stats. Maybe the issue was fixed only for services deployed on the shared servers?

**Comment by dpetrick** [comment]
Self-hosted deployments will not show stats as they're not part of our system.

**Comment by agonbina** [comment]
@dpetrick I see ... I thought you expose some endpoint in the "self hosted deployment" where you can pull stats from and show them in the dashboard.

If this feature does not work for self hosted deployments, is there any good arguments for someone who does not used the "hosted cloud deployment" to switch to the "Team plan" besides increased support availability? :)

**Comment by marktani** [comment]
Thanks a lot for your feedback @agonbina - let me clarify the situation:

We recently identified and fixed an issue with the dashboard that occured to services on the demo server.
We will very soon [add dashboard support for Prisma Cloud Connect](https://github.com/prismagraphql/prisma-cloud-feedback/issues/154).

The team plan for Prisma Cloud allows you to collaborate on Prisma services with bigger teams and will get more and more features over time - stay tuned on our blog for this! :slightly_smiling_face:
