### ISSUE TITLE
Servers stuck in provisioning or deleting

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma-cloud-feedback#147]
We are logging an increased number of servers stuck in provisioning or deleting currently.
We are already investigating the root cause of this problem.

Please reach out to support@prisma.io, or the chat from within the Console, if your server is stuck in provisioning or deleting, or you notice something else that is unexpected.

When your server is stuck in provisioning, please don't create a second server connecting to the same database.

**Comment by dpetrick** [comment]
This should no longer be an issue. @obibring do you still face issues and / or have clusters in an endless provisioning or deletion state?
