### ISSUE TITLE
Issues during onboarding

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma-cloud-feedback#159]
It sometimes happen that workspaces already have deployed services, but they still show this screen:

![image](https://user-images.githubusercontent.com/1780597/40978285-7f7d565e-68d3-11e8-9703-f4d7300a72cd.png)

We should 

* [ ] investigate why this happens and fix the underlying issue
* [ ] add a "Skip" button so this can be easily resolved by the user

**Comment by andrewlee7** [comment]
Any update on this?

**Comment by marktani** [comment]
Hey @andrewlee7, we added a Skip button can you try again? 🙂

**Comment by andrewlee7** [comment]
I am not seeing a skip button. I have refreshed as well as completely logged out and then back in again. Whenever I am on the services tab I am completely blocked by the deploy a service message.

**Comment by andrewlee7** [comment]
<img width="1042" alt="screen shot 2018-06-12 at 7 51 18 am" src="https://user-images.githubusercontent.com/394984/41298072-70f5d04c-6e15-11e8-9f35-c65981bda47a.png">

**Comment by timsuchanek** [comment]
Thanks for reporting @andrewlee7!
Due to a bug in the backend, the services couldn't be retrieved correctly by the frontend.
This is now fixed, you should be able to see your services as expected 🙂 
Let us know if you face any other issue!

**Comment by andrewlee7** [comment]
Thanks, looks good now
