### ISSUE TITLE
Region n/a for US cluster and self-hosted cluster. 

### ISSUE THREAD

**Issue by divyenduz** [prismagraphql/prisma-cloud-feedback#167]
<img width="996" alt="screen shot 2018-06-26 at 7 03 41 pm" src="https://user-images.githubusercontent.com/746482/41927891-ce7d4222-7973-11e8-818f-33b430cdd30d.png">

**Comment by timsuchanek** [comment]
Thanks for reporting! Fixed in latest version :)
