### ISSUE TITLE
It's around 200-300 times slower than a PHP back-end - is it meant to be?

### ISSUE THREAD

**Issue by MitchEff** [prismagraphql/prisma-cloud-feedback#177]
I've just opened up a new Prisma Cloud account, and so far my database has a few tables/data types but is nearly empty (3-5 records total). 

Opening the 'Data browser' in Chrome takes around 40 seconds, and posting a simple query takes maybe 4-5 seconds or so. We're trying to work out whether to go with Prisma or use a Laravel (PHP) back-end for all our new client work, but at the moment Laravel is several hundred times or so faster, so it kind of seems like a no-brainer. 

Is it supposed to be like this? I can't imagine it's a set-up issue, as I'm trying things out straight from the browser/playground.

**Comment by timsuchanek** [comment]
Thanks for asking this important question @MitchEff !
Where is your Prisma service hosted? Note that the demo server uses throttling (of 10 requests per 10 seconds) and that this could affect what you see. Though the times that you're reporting are very unusual.

Even with the demo server, the Databrowser should load in about 2 seconds.

Another possibility could be, that you use the Heroku integration. Note that heroku puts instances to sleep when they're not being used.

**Comment by marktani** [comment]
Sure, go ahead and try it out 🙂 But note that both the demo server in US and EU do not optimize for request performance, they are simply a means to get up and running quickly. It does sound like you are running into the rate limit that @timsuchanek mentioned.

You can try to set up a free Heroku server and check the performance there (and keep in mind that Heroku has a sleep cooldown).

Let's continue the discussion here: https://www.prisma.io/forum/t/prisma-cloud-is-around-200-300-times-slower-than-a-php-back-end-for-me-is-it-meant-to-be/3930?u=nilan 🙂
