### ISSUE TITLE
Unable to update servers to 1.11.1

### ISSUE THREAD

**Issue by Huvik** [prismagraphql/prisma-cloud-feedback#182]
I am unable to update cluster from version `1.10.2` to `1.11.1`, because select is empty. Api returns empty upgrades: 
![](https://i.imgur.com/q08ovOh.png)

**Comment by marktani** [comment]
Prisma servers managed in Prisma Cloud can only be upgrade to `1.10.2` currently.

**Comment by Huvik** [comment]
Ah, okay I didn't know that, because I was thinking that all non-beta releases are possible for cloud :)

**Comment by marktani** [comment]
Closing as duplicate of https://github.com/prismagraphql/prisma-cloud-feedback/issues/186
