### ISSUE TITLE
Unable to view servers after creating new server

### ISSUE THREAD

**Issue by hoodsy** [prismagraphql/prisma-cloud-feedback#195]
After creating a new server, I was unable to view my list of servers and saw the following errors in the console:

![screen shot 2018-07-31 at 2 26 22 pm](https://user-images.githubusercontent.com/4467642/43479163-b8eeab38-94cd-11e8-9a8e-c21fc13d1bd3.png)
![screen shot 2018-07-31 at 2 28 49 pm](https://user-images.githubusercontent.com/4467642/43479308-16d37ddc-94ce-11e8-83a6-0b6f398d10bb.png)

**Comment by hoodsy** [comment]
Update: I tried to create a new Workspace and Server as a workaround, but can't get to the `Create a Server` step:
![screen shot 2018-08-03 at 11 44 27 am](https://user-images.githubusercontent.com/4467642/43652255-ab3217a4-9712-11e8-8c8c-4f16cf42fe3e.png)

**Comment by timsuchanek** [comment]
Thanks for reporting @hoodsy ! We just deployed a fix for this! Let me know if it's working for you :)

**Comment by hoodsy** [comment]
this works! thanks @timsuchanek

**Comment by hoodsy** [comment]
One note – as I'm in the `Servers` tab, it refreshes intermittently, showing the loading spinner. Maybe this is intentional, but I figured I'd mention it. Console errors are triggered when the loading spinner is visible.

![screen shot 2018-08-06 at 9 39 47 am](https://user-images.githubusercontent.com/4467642/43719797-b28266ca-995c-11e8-9c36-fb20a4d707f0.png)
