### ISSUE TITLE
Deployment with Maria DB

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma-cloud-feedback#30]
Looks like it doesn't work. I want to reproduce this.

**Comment by mfts** [comment]
Any updates on this @marktani ?

**Comment by marktani** [comment]
I wasn't able to reproduce - fundamentally it should work, if you hit any problems please report back :slightly_smiling_face:

**Comment by sjortiz** [comment]
when you use MariaDB in the docker compose and you try to deploy it doesn't work, it creates the workspace but doesn't deploy the schema
https://cl.ly/1M1c340J1B1y

here is the console output from the deploy
https://cl.ly/1W3h0z293b2u

@marktani
