### ISSUE TITLE
Getting errors when trying to link nodes via data browser

### ISSUE THREAD

**Issue by reinvanimschoot** [prismagraphql/prisma-cloud-feedback#67]
I'm receiving an error when I want to add a node as a relation to another node. 

In my example, I tried adding the id of a Translation to the TranslationCollection but I get the following error:

![screen shot 2018-02-28 at 16 17 32](https://user-images.githubusercontent.com/35171567/36851543-bd0e3642-1d69-11e8-81f6-be6b910f5366.png)

**Comment by timsuchanek** [comment]
Thanks for reporting! This is fixed in the latest version.
